package cnf

// These are the contents to be written into the default config file
// when it does not exist.
var sample = `# This is the autogenerated config file for OMG

[custom]
# Here you can bind new OMG commands to your own scripts
# This would make 'omg mycmd' run 'scripts/myscript.sh'
#   mycmd = "scripts/myscript.sh"
`
