package input

// These are the contents to be written into the default config file
// when it does not exist.
var sample = `# This is the autogenerated config file for OMG

[custom]
# Here you can bind new OMG commands to your own scripts

# This would make 'omg mycmd' run 'scripts/myscript.sh'
#   mycmd = "scripts/myscript.sh"

# This would make 'omg serve' run Brunch in server mode
#   serve = "node_modules/brunch/bin/brunch w --server"

# Any further flags or arguments are passed to the given command
# With this line
#   brunch = "node_modules/brunch/bin/brunch"
# you could make 'omg brunch w --server' run the same as before

[servers]
# Here you can specify a fixed list of servers, like this:
# serverA = { ip="1.1.1.1" }
# serverB = { ip="1.1.1.2" }

# Or you could give a GCE project id and a regexp
# gceProject = "project-id"
# match = "regexstr"

[goto]
# You can customize the actual command to open a terminal
# Syntax is std Go templates (https://golang.org/pkg/text/template/)
# OMG will replace 'Title' and 'Command'
# terminal = "terminator -T '{{.Title}}' -e '{{.Command}}'"
`
